const headerCols1 = [
  'field name',
  'irog delivered',
  'start time',
  'end time',
  'number of items',
  'pickers',
  'no of trees',
  'yellow',
  'green',
  'over ripe',
  'delivered',
  'remarks',
]
const dataRows1 = [
  {
    field_name: 'field 1',
    irog_delivered: '15260',
    start_time: '8:00 am',
    end_time: '12:00 pm',
    number_of_items: '170',
    pickers: '12',
    no_of_trees: '249',
    yellow: '11040',
    green: '1490',
    over_ripe: '2240',
    delivered: '12770',
    remarks: 'loss 40/wet'
  },
]
const headerCols2 = [
  'field name',
  'irog delivered',
  'start time',
  'end time',
  'number of items',
  'pickers',
  'no of trees',
  'yellow',
  'green',
  'over ripe',
  'delivered',
  'remarks',
]
const dataRows2 = [
  {
    time_start: '',
    time_end: '',
    material_batch_no: '',
    origin: '',
    received_time: '',
    pieces_of_f1: '170',
    pieces_of_f2: '12',
    pieces_of_f3: '12',
    pieces_of_f4: '12',
    pieces_of_f5: '12',
    mango_a: '249',
    mango_c: '249',
    extra: '11040',
    gross_wt: '1490',
    green_tea: '2240',
    delivered: '12770',
    material_quantity: '',
    still_no: '',
    harvest_date: '',
    harvest_time: '',
    no_of_trees: '',
    demo: '',
    first_g: '',
    second_g: '',
    third_g: '',
    green: '',
    over_ripe_tea: '',
    mose: '',
    over_ripe: '',
    remarks: 'loss 40/wet',
    delivered: ''
  },
]

export default {
  headerCols1,
  dataRows1,
}